openapi: 3.0.3
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://example.com
paths:
  /transactions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTransaction'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        422:
          description: Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
  /attach/{key}:
    post:
      parameters:
        - $ref: '#/components/parameters/key'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                attachments:
                  type: array
                  items:
                    $ref: '#/components/schemas/Attachment'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        422:
          description: Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
  /finish/{key}/{foo}:
    post:
      parameters:
        - $ref: '#/components/parameters/key'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        422:
          description: Failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'

components:
  parameters:
    key:
      name: key
      in: path
      schema:
        type: string
        format: uuid
      required: true
  schemas:
    Attachment:
      oneOf:
        - $ref: '#/components/schemas/Base64'
        - $ref: '#/components/schemas/Link'
    Base64:
      type: object
      properties:
        name:
          type: string
        data:
          type: string
          format: byte
    Content:
      oneOf:
        - $ref: '#/components/schemas/Base64'
        - $ref: '#/components/schemas/Link'
    Error:
      description: error description
      type: string
      example:
        - is not valid
        - too long
    Errors:
      type: object
      additionalProperties:
        description: field name
        type: array
        items:
          $ref: '#/components/schemas/Error'
    Document:
      type: object
      properties:
        name:
          type: string
          enum:
            - cpf
            - rg
        value:
          type: string
    Link:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
          format: uri
    Transaction:
      allOf:
        - type: object
          properties:
            key:
              type: string
              format: uuid
        - $ref: '#components/schemas/NewTransaction'
    NewTransaction:
      type: object
      properties:
        name:
          type: string
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'
          minItems: 1
        contents:
          type: array
          items:
            $ref: '#/components/schemas/Content'
          minItems: 1
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
      required:
        - name
        - documents
        - contents